// Refreshes src/data/stats.js with ranked matchup win rates and hero win, ban and pick rates.
// Data comes from the Rone Arena API (https://arena.rone.dev). Game data © Moonton.
//
// Usage: npm run update-stats
// Optional: STATS_RANK=all|epic|legend|mythic|honor|glory (default mythic), STATS_DAYS=1|3|7|15|30 (default 15)
import fs from 'node:fs';
import { HEROES } from '../src/data/heroes.js';

const API = 'https://arena.rone.dev/api';
const RANK = process.env.STATS_RANK || 'mythic';
const DAYS = Number(process.env.STATS_DAYS || 15);
const CONCURRENCY = 4;
const OUT = new URL('../src/data/stats.js', import.meta.url);

const order = HEROES.map((hero) => hero.id);
const indexOf = new Map(order.map((id, index) => [id, index]));
const idByApiId = new Map(HEROES.map((hero) => [hero.apiId, hero.id]));
const round3 = (value) => Math.round(value * 1000) / 1000;

async function getData(path) {
  for (let attempt = 1; attempt <= 4; attempt += 1) {
    try {
      const response = await fetch(`${API}${path}`, { headers: { accept: 'application/json' } });
      if (!response.ok) throw new Error(`HTTP ${response.status}`);
      const json = await response.json();
      if (json.code !== 0) throw new Error(json.message || 'API error');
      return json.data;
    } catch (error) {
      if (attempt === 4) throw new Error(`${path}: ${error.message}`);
      await new Promise((resolve) => setTimeout(resolve, 1500 * attempt));
    }
  }
}

async function forEachLimited(items, limit, task) {
  const queue = [...items];
  await Promise.all(Array.from({ length: limit }, async () => {
    while (queue.length) await task(queue.shift());
  }));
}

// Row for one hero: how its win rate changes against every other hero, in tenths of a point.
async function fetchMatchupRow(hero) {
  const data = await getData(`/academy/heroes/${hero.apiId}/counters?rank=${RANK}`);
  const record = data.records[0] && data.records[0].data;
  if (!record) throw new Error(`no matchup data for ${hero.name}`);
  const row = new Array(order.length);
  record.sub_hero.forEach((entry) => {
    const enemyId = idByApiId.get(entry.heroid);
    if (enemyId && enemyId !== hero.id) row[indexOf.get(enemyId)] = Math.round(entry.increase_win_rate * 1000);
  });
  return row;
}

async function fetchMeta() {
  const meta = {};
  for (let index = 1; index <= 10; index += 1) {
    const data = await getData(`/heroes/rank?rank=${RANK}&days=${DAYS}&sort_field=win_rate&sort_order=desc&size=50&index=${index}`);
    data.records.forEach(({ data: stats }) => {
      const heroId = idByApiId.get(stats.main_heroid);
      if (!heroId) return;
      meta[heroId] = {
        winRate: round3(stats.main_hero_win_rate),
        banRate: round3(stats.main_hero_ban_rate),
        pickRate: round3(stats.main_hero_appearance_rate),
      };
    });
    if (!data.records.length || Object.keys(meta).length >= data.total) break;
  }
  return meta;
}

const rows = new Array(order.length);
let done = 0;
await forEachLimited(HEROES, CONCURRENCY, async (hero) => {
  rows[indexOf.get(hero.id)] = await fetchMatchupRow(hero);
  done += 1;
  if (done % 20 === 0 || done === HEROES.length) console.log(`matchups: ${done}/${HEROES.length}`);
});
const meta = await fetchMeta();

const missingMeta = order.filter((id) => !meta[id]);
if (missingMeta.length) throw new Error(`no win rates for: ${missingMeta.join(', ')}`);
order.forEach((id, index) => {
  const known = rows[index].filter((value) => value !== undefined).length;
  if (known < 60) console.warn(`warning: ${id} only has ${known} matchups`);
});

const updated = new Date().toISOString().slice(0, 10);
const rowText = (row) => `[${Array.from(row, (value) => (value === undefined ? '' : value)).join(',')}]`;
const metaText = order
  .map((id) => `  ${JSON.stringify(id)}: { winRate: ${meta[id].winRate}, banRate: ${meta[id].banRate}, pickRate: ${meta[id].pickRate} },`)
  .join('\n');

const source = `// Generated by \`npm run update-stats\` on ${updated}. Do not edit by hand.
// ${RANK[0].toUpperCase()}${RANK.slice(1)}-rank statistics from the Rone Arena API (https://arena.rone.dev).
// Game data © Moonton (Mobile Legends: Bang Bang). API maintained by ridwaanhall / RoneAI.
/* eslint-disable no-sparse-arrays */

export const STATS_INFO = { rank: ${JSON.stringify(RANK)}, days: ${DAYS}, updated: ${JSON.stringify(updated)} };

// Hero ids, in the order MATCHUP_TENTHS uses for its rows and columns.
export const STATS_HERO_ORDER = ${JSON.stringify(order)};

// MATCHUP_TENTHS[a][b]: how much hero a's win rate changes when facing hero b, in tenths of a percentage
// point (39 means +3.9 points). Empty entries have no data.
export const MATCHUP_TENTHS = [
${rows.map((row) => `  ${rowText(row)},`).join('\n')}
];

// Win, ban and pick rates over the last ${DAYS} days, from 0 to 1.
export const HERO_META = {
${metaText}
};
`;

fs.writeFileSync(OUT, source);
console.log(`wrote src/data/stats.js: ${order.length} heroes, ${(source.length / 1024).toFixed(0)} KB, ${RANK} rank, ${DAYS} days`);
